version: '3.4'

services:
  web-api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "7034:443"
      - "7033:80"

  frontend:
    container_name: client
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./Frontend/spacexplorer/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      
      
      